### ISSUE TITLE
JSX Presets file required

### ISSUE THREAD

**Issue by itsderek23** [UXPin/uxpin-merge-tools#195]
Components need a presets directory and .jsx file with a specific name and in a specific format in order for Merge to be able to render the component.

Whilst this is understandable, it prevents a "just-work" approach.

Possible solution:

Could the CLI auto-generate the the directories and preset files and attempt to produce something that would define the component in a default state? Then all the user would have to do is make tweaks to the already working solution.

**Comment by matthewchigira** [comment]
Also logged here: https://github.com/UXPin/uxpin-merge-tools/issues/228
