### ISSUE TITLE
`uxpin-merge push` support for "detatched HEAD" state

### ISSUE THREAD

**Issue by itsderek23** [UXPin/uxpin-merge-tools#206]
In #194, I mentioned the same error occurs when running `uxpin-merge push` from a detached HEAD git repo state. This state is common when running via a CI system as they checkout a specific commit, not a ref to a branch.

Because of this, `uxpin-merge push` may be unlikely to work currently when triggered via CI.

I'm creating a dedicated issue for this as it is a more immediate blocker to running Merge within CI than branch support and there's less tradeoffs to think through versus branch `push` support.

**Comment by itsderek23** [comment]
Hey @vados-xenon - how do you feel about attempting this one? If so, I'll assign to you. If not, I can get started on this one.

**Comment by vados-xenon** [comment]
Hey @itsderek23 that sounds good, please assign away!

**Comment by vados-xenon** [comment]
Given the revelations [in the server-side issue](https://github.com/UXPin/uxpin-issues/issues/15) it looks like the crux of this work is actually going to be on the backend?

I've looked at the code and it's actually just a warning -- it doesn't stop you from actually pushing anything (until you push and can't go back?) -- it's more that you can get into a broken state if you push from `master`, then from `some-branch`, then from `master` again (or another branch) if the backend detects some differences
