### ISSUE TITLE
Init Command

### ISSUE THREAD

**Issue by matthewchigira** [UXPin/uxpin-merge-tools#227]
Could we create `init` mode in the CLI (we currently have modes such as `push` or `dump`) which generates a default `uxpin.config.js` and our "default" `uxpin.webpack.config.js` file? Perhaps we could also create the `UXPinWrapper` component file too.

This would save new users the hassle of manually having to create these files, and would give people a better starting point.

For the config file it would be good to stub out a "General" category with a single, commented-out component e.g. `// 'src/components/Button/Button.js'` showing best-practises. Also we could add the paths to webpack and wrapper files in this config too.

**Comment by mzah** [comment]
I did created something like this:
https://github.com/UXPin/uxpin-merge-tools/pull/233
Rob looked on it at said that it looks fine
I did try to use it with my own library (and works fine)
Do you expect something more that simple usage of default/predefined cfg files in this task?

**Comment by naohiro-t** [comment]
@mzah - Talked with @matthewchigira . Can we add a Button example with this command? (probably we can use https://github.com/UXPin/uxpin-merge-boilerplate/tree/master/src/Button ? or much simpler one might be better... )

That should let users to see what's like to use merge instantly with experiment mode :)

**Comment by mzah** [comment]
kk i added button (simpler than this one in boilerplate). Rob reviewed me again also

**Comment by matthewchigira** [comment]
Closed by #233
