### ISSUE TITLE
TypeScript: Support component with non inlined export statement

### ISSUE THREAD

**Issue by naohiro-t** [UXPin/uxpin-merge-tools#245]
e.g. We don't detect this case because 

With our `isExported` function, we only check the inline export statement.
https://github.com/UXPin/uxpin-merge-tools/blob/8b8843405d294b8efb24fb7611e9b5bc370a3c51/packages/uxpin-merge-cli/src/steps/serialization/component/implementation/typescript/component/isExported.ts#L4-L9

And here, we use `isExported` to check.
https://github.com/UXPin/uxpin-merge-tools/blob/8b8843405d294b8efb24fb7611e9b5bc370a3c51/packages/uxpin-merge-cli/src/steps/serialization/component/implementation/typescript/component/findExportedFunctionWithName.ts#L5-L16

Sample component. 
```
import * as React from 'react';

export interface Props {
  appearance: 'secondary' | 'primary' | 'link';
}

class Component extends React.Component<Props> {

  public static defaultProps: Partial<Props> = {
    appearance: 'secondary',
  };

  public render(): JSX.Element {
    const { appearance } = this.props;
    return (
      <div>
        <button className={appearance}>
           Hello
        </button>
      </div>
    );
  }
}

export default Component;
```

Currently, you'll get `Error: No component found!`

**Comment by matthewchigira** [comment]
Closed by [248](https://github.com/UXPin/uxpin-merge-tools/pull/248)
